language: csharp
mono: none
dotnet: 3.1.402
solution: CashBack.sln
before_script:
    - sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
install:
    - dotnet restore
    - dotnet tool install coveralls.net --version 2.0.0-beta0002 --tool-path tools   
script:
    - dotnet build
    - cd minicover
    - dotnet restore
    - dotnet minicover instrument --workdir ../ --sources ./**/*.cs --exclude-sources ./**/Tests/*.cs --exclude-sources ./**/Models/*.cs --exclude-sources ./**/DTO/*.cs --exclude-sources ./**/Attributes/*.cs --exclude-sources ./**/Startup.cs --exclude-sources ./**/Program.cs --exclude-sources ./**/Migrations/*.cs
    - dotnet minicover reset
    - cd ..
    - dotnet test --no-build
    - cd minicover
    - dotnet minicover report --workdir ../
    - dotnet minicover coverallsreport --root-path ../ --workdir ../ --service-name "travis-ci" --service-job-id "$TRAVIS_JOB_ID"