language: csharp
mono: none
dist: xenial
dotnet: 3.1
before_script:
  - sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test CashBack.Data.Test/CashBack.Data.Test.csproj
